version: '3'

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  client:
    build: ./client
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    depends_on:
      - server

 test:
    build: ./server
    command: ["npm", "test"]