/*
 * @Description: 
 * @Version: 1.0
 * @Author: shenkai03
 * @Date: 2024-06-04 21:03:51
 * @LastEditors: shenkai03
 * @LastEditTime: 2024-06-04 21:19:52
 * @FilePath: /siteman/client/src/app/layout.tsx
 * Copyright (C) 2024 shenkai03. All rights reserved.
 */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import '@radix-ui/themes/styles.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Theme>
      <body className={inter.className}>{children}</body>
      </Theme>
    </html>
  );
}
